"""add content_hash to documents

Revision ID: c0137c3b89e9
Revises: 21789b952a91
Create Date: 2025-12-16 18:55:49.528457

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c0137c3b89e9"
down_revision: Union[str, Sequence[str], None] = "21789b952a91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
